### ISSUE TITLE
Launch checklist

### ISSUE THREAD

**Issue by kytrinyx** [exercism/xscheme#10]
In order to launch we should have:

- [x] scheme as a submodule in [x-api](https://github.com/exercism/x-api/tree/master/problems)
- [x] at least 10 problems
- [x] a "how to get started" topic in the [help repo](https://github.com/exercism/docs) repo (`app/pages/languages/getting-started-with-scheme.md`)
- [x] one to a handful of people willing to check exercism regularly (daily?) for nitpicks to ensure that the track gets off on the right foot
- [x] toggle `"active"` to `true` in `config.json`

Some tracks have been more successful than others, and I believe the key features of the successful tracks are:

* Each submission receives feedback quickly, preferably within the first 24 hours.
* The nitpicks do not direct users to do specific things, but rather ask questions challenging people to think about different aspects of their solution, or explore new aspects of the language.

**Comment by canweriotnow** [comment]
@kytrinyx working on the getting-started topic, what should the value of "ordinal" be in the YAML front matter?

**Comment by kytrinyx** [comment]
For now I've been assigning ordinals such that the languages end up in alphabetical order.

**Comment by canweriotnow** [comment]
Gotcha. So for the moment I'll use something between 'scala' and 'swift', closer to Scala :)

I think I'm going to go ahead and write it for Guile, and update if #11 leads to a consensus that another Scheme is more optimal. So expect a PR before too long :smiley_cat:

**Comment by kytrinyx** [comment]
That sounds good, thanks!

**Comment by canweriotnow** [comment]
80% there on problem count, I think as soon as I finish with this sprint at work I'll try to knock out two more and get teh SETUP.md finished. Wish me luck :tired_face:

**Comment by kytrinyx** [comment]
w00t :) (and good luck!)

**Comment by canweriotnow** [comment]
1 problem to go...

**Comment by canweriotnow** [comment]
Well, last thing on the checklist is toggling active to true...

I'll check for submissions at least every 24-48 hours and actively recruit others, maybe some of the active Lisp and Clojure folks will jump in. I'm not above cajoling.

**Comment by canweriotnow** [comment]
Ugh... @kytrinyx maybe blocking for #21 - Add submodule was checked off (pretty sure it wasn't me) but I don't see it in [x-api][1] - am I missing something?

[1]: https://github.com/exercism/x-api/tree/master/problems

**Comment by kytrinyx** [comment]
I did that a while back. Now it'll just go live the next time I update the submodules (which is in 30 seconds).

**Comment by kytrinyx** [comment]
I was wrong, I didn't do it a while back. Fixing it now.

**Comment by kytrinyx** [comment]
Deployed. `exercism fetch scheme` gives me the first exercise.

**Comment by canweriotnow** [comment]
w00t!
